---
- hosts: webservers
  become: yes
  become_user: nshariff
  tasks:
    - name: Updates apt cache
      action: apt update_cache=true
    - name: Install Apache
      apt:
        name: apache2
        state: latest
    - name: Start Apache server
      service:
        name: apache2
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
      notify:
        - restart httd
