---
- hosts: webservers 
  become: yes
  become_user: nshariff
  tasks:
    - name: Update Repository cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
    - name: Install Apache
      apt:
        name: apache2
        state: latest
    - name: Start Apache server
      service:
        name: apache2
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
      notify:
        - restart httd
